### ISSUE TITLE
datasette-lite: sqlite-error on row

### ISSUE THREAD

**Issue by ross-spencer** [nasawakeupcalls/nasawakeupcalls.data#24]
Error: 

```
Error
Traceback (most recent call last):
  File "/lib/python3.10/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/lib/python3.10/asyncio/tasks.py", line 232, in __step
    result = coro.send(None)
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 500, in eval_code_async
    await CodeRunner(
  File "/lib/python3.10/site-packages/_pyodide/_base.py", line 353, in run_async
    await coroutine
  File "<exec>", line 42, in <module>
  File "/lib/python3.10/site-packages/sqlite_utils/db.py", line 2942, in insert_all
    chunk = list(chunk)
  File "/lib/python3.10/site-packages/sqlite_utils/db.py", line 3471, in fix_square_braces
    for record in records:
  File "/lib/python3.10/site-packages/sqlite_utils/utils.py", line 323, in wrap
    for row in iterator:
  File "/lib/python3.10/site-packages/sqlite_utils/utils.py", line 203, in _extra_key_strategy
    for row in reader:
  File "/lib/python3.10/site-packages/sqlite_utils/utils.py", line 214, in _extra_key_strategy
    raise RowError(
sqlite_utils.utils.RowError: Row {'Dates': '1969-05-25', 'Program': 'APOLLO', 'Mission': 'APOLLO 10', 'Artist': 'Unidentified', 'Song': 'Come Fly With Me', 'Comment': 'Zip-a-Dee-Doo-Dah was sent from mission control to the crew, but only after the crew themselves, awake before mission control\'s first transmission, sent \'Come Fly with Me\'. The following message attached: "Good morning', 'Genre': ' good morning! This is Tom', 'Style': ' John', 'Year': ' and Gene from KAT 10', 'Discogs Master': ' broadcasting again from approximately 140', 'Discogs URI': '000 miles [259'} contained these extra values: ['280 km] out into the universe. It’s a beautiful day out here', " and it appears that it might be a beautiful day down in Mother Earth country. For those of you who are not just ready for work or are just getting up: Get up lazy bones! It's time you got up! Big day ahead! And the thought for today is: Remember", ' National Secretary’s Week was last month!"""', '', '', '', '', 'https://www.discogs.com/label/784508-Come-Fly-With-Me']
```

URL: https://lite.datasette.io/?csv=https%3A%2F%2Fraw.githubusercontent.com%2Fnasawakeupcalls%2Fnasawakeupcalls.data%2Fmain%2Fnasawakeupcalls.csv

**Comment by ross-spencer** [comment]
Connected to: https://github.com/nasawakeupcalls/nasawakeupcalls.github.io/issues/11

(Turns out I already tried this!!)

Closing this issue as it seems to now have resolved itself! 🥳
